### ISSUE TITLE
Dynamic RAILS_ENV

### ISSUE THREAD

**Issue by sblackstone** [mtgrosser/passenger-systemd#1]
More of a comment than an issue..

I've been trying to combine this script with a capistrano, standalone passenger, and puppet...

The one stumbling block I have is setting the RAILS_ENV on a per-directory basis...

I'd love to be able to do systemctl restart passenger@app_name.staging and then somehow split parameter name within unit file to setup the environment, but this seems to be tricky..

**Comment by mtgrosser** [comment]
Setting the `RAILS_ENV` can be accomplished using `PASSENGER_OPTS` in your app's `config/passenger.env`:

`PASSENGER_OPTS="--environment development"`
